### PR TITLE
Reduce authors to main + other contributors

### LINKED ISSUE #278: Ugly warning when using tower.nf
### Description of the bug

```
WARN: Tower request field `workflow.manifest.author` exceeds expected size | offending value: `James A. Fellows Yates, Sofia Stamouli, Moritz E. Beber, Lauri Mesilaakso, Thomas A. Christensen II, Jianhong Ou, Mahwash Jamy, Maxime Borry, Rafal Stepien, Tanja Normark`, size: 170 (max: 150)
```

### Command used and terminal output

_No response_

### Relevant files

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by jfy133**
Due to tower limitation producing ugly warning

Minor so doesn't need CHANGELOG

Closes #278 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/taxprofiler/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/taxprofiler _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by Midnighter** [comment]
Should we list somewhere who is part of the nf-core/taxprofiler team? Might be a little offensive to just remove the names otherwise.

**Comment by jfy133** [comment]
https://github.com/nf-core/taxprofiler#credits ?? 

Or I could rephrase to taxprofielr contributors rather than team?

**Comment by Midnighter** [comment]
I'd either rephrase team to contributors or change the credits section to have:

#### Team

* list of people

**Review by sofstam — APPROVED** [review]

**Comment by sofstam** [comment]
I like @Midnighter idea about Team and list of people.

**Comment by jfy133** [comment]
@nf-core-bot fix linting plz

**Pull request merged**
