### PR TITLE
Drop db_params patterns for bracken and kmcp

### PR DESCRIPTION
**Pull request by LilyAnderssonLee**
Fix the issue #475 

The original definitions of db_params of `bracken` and `kmcp` in `db_check.nf``
```
    if ( row.tool == 'bracken' && row.db_params && !row.db_params.contains(";") )  error("[nf-core/taxprofiler] ERROR: Invalid database db_params entry. Bracken requires a semi-colon if passing parameter. Error in: ${row}")
    if ( row.tool == 'kmcp' && row.db_params && row.db_params.matches(".*;\$"))  error ("[nf-core/taxprofiler] ERROR: Invalid database db_params entry. KMCP only requires a semi-colon if passing arguments to KMCP profile, in cases of which the arguments should go after the semi-colon. Error in: ${row}")

```

The database.csv used in this test:

```
tool,db_name,db_params,db_path
bracken,db1,;-r 150,https://github.com/nf-core/test-datasets/raw/taxprofiler/data/database/bracken/testdb-bracken.tar.gz
kraken2,db2,--quick,https://github.com/nf-core/test-datasets/raw/taxprofiler/data/database/kraken2/testdb-kraken2.tar.gz
kmcp,db1,;\$--min-kmers 30;\$--min-query-cov 0.5,https://github.com/nf-core/test-datasets/raw/taxprofiler/data/database/kmcp/test-db-kmcp.tar.gz

```

The Bracken output files in this test:
image

kmcp output files in this test:
image

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/taxprofiler/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/taxprofiler _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jfy133** [comment]
I'm trying work out the best way to do this now: 

Reading our docs:

image

And comparing with the code, it looks like to me actually we don't _require_ the `;` even if you're running bracken. We did in the past but we relaxed: you only need a semi-colon if you want to supply to both kraken/bracken or _just_ kraken. If you want to send to just kraken, no semi-0colon needed.

So in this case the new pattern wouldn't work with that, as it's requiringa  semi-colon

Hence... I think we just need to remove the pattenr entirely? What do you think?

**Comment by LilyAnderssonLee** [comment]
It sounds wise to me to remove the `db_parmas` patters for `bracken` and `kmcp`.

**Review by jfy133 — APPROVED** [review]

**Comment by jfy133** [comment]
Thank you @LilyAnderssonLee ! I think we can do a patch release already (if you don't have time I will do it tomorrow evening)

**Comment by jfy133** [comment]
Unless @sofstam  would have time

**Comment by LilyAnderssonLee** [comment]
@jfy133 I have some time tomorrow morning before 10:00. I hope I can manage a patch release before then.

**Comment by sofstam** [comment]
I am available tomorrow and I can take over from Lili after 10:00 :)

**Pull request merged**
