### PR TITLE
Update ganon

### LINKED ISSUE #401: Allow hibf in ganon?
### Description of feature

Thank you for a really nice tool. 

I was going to try out ganon and was generating a database using their recommendation for refseq https://pirovc.github.io/ganon/default_databases/. 

```
ganon build --source refseq --organism-group archaea bacteria fungi viral --threads 48 --hibf --level species --db-prefix abfv_rs
```

When using it in taxprofiler i got errrors, I realized it was due to taxprofiler looking for ibf while i have hibf. I regenerated the database without the hibf but when testing it kept crashing due to depleted memory (running alone in a node with 512 GiB ram using an insilco sample of 6 species with 1M reads in total). Using the hibf version it runs fine. 

Would it be possible to include hibf for ganon in taxprofiler?

### PR DESCRIPTION
**Pull request by sofstam**
This PR closes #401

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/taxprofiler/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/taxprofiler _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by jfy133 — COMMENTED** [review]
- Will need OUTPUT.md update due to changing outout files
- Missing CHANGELOG update with dependency version bump

**Comment by sofstam** [comment]
Thanks for the quick review.

**Comment by sofstam** [comment]
Tests are not passing for taxpasta, the output formats are the same in the newest version so it should not have been an issue, looking closer into this.
Screenshot 2024-02-08 at 16 21 50

**Comment by jfy133** [comment]
It could be the database we have is incompatible? Could you check the actual ganon report files look OK?

**Comment by sofstam** [comment]
I tested locally with the minimal data and no issue with taxpasta

`nextflow run main.nf -profile test,docker --run_ganon --outdir test_ganon_output -resume`

The ganon files look ok. I will run the pipeline with `test_full` profile.

**Pull request closed without merging**
