### PR TITLE
Add samtools stats for short-reads

### LINKED ISSUE #157: Include stats for short-reads in Multiqc report
### Description of feature

Add stats information for short-reads in Multiqc report.

### PR DESCRIPTION
**Pull request by sofstam**
Closes #157

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/taxprofiler/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/taxprofiler _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by Midnighter** [comment]
I know it'd be a bunch more work but how about adding a subworkflow for this to nf-core/modules and then using the subworkflow here and for the long reads?

**Comment by sofstam** [comment]
Can we update this one? 
https://github.com/nf-core/modules/tree/master/subworkflows/nf-core/bam_stats_samtools

Or shall we have a separate one for short-reads `bowtie2_bam_stats_samtools`  and one for long-reads `minimap2_bam_stats_samtools`?

I can add it as subworkflow but I am thinking that since the stats for long-reads are already merged maybe we can convert both PRs to subworkflows in the v1.1 release of taxprofiler?

**Comment by Midnighter** [comment]
> Can we update this one?
https://github.com/nf-core/modules/tree/master/subworkflows/nf-core/bam_stats_samtools

You'll have to talk to @matthdsm I'm not quite sure about the similarities/differences right now.

> I can add it as subworkflow but I am thinking that since the stats for long-reads are already merged maybe we can convert both PRs to subworkflows in the v1.1 release of taxprofiler?

Sounds reasonable, I'll make an issue for it 🙂

**Comment by matthdsm** [comment]
I don't think I'm really the one to make any decisions about what can and can't be a subworkflow. I suggest opening a discussion in the #subworkflows channel slack. I'd be happy to chime in with an opinion there!

**Review by jfy133 — CHANGES_REQUESTED** [review]
I'm concerned that there is no customisation of `prefix` that we could overwrite stats files (i.e., multiple runs of the same sample, so each have a stats file, but we only use the sample ID for making stats files), (this apply for long reads too).

Should update README to include this step (and the diagram)!

Otherwise LGTM

**Comment by jfy133** [comment]
> I'm concerned that there is no customisation of prefix that we could overwrite stats files (i.e., multiple runs of the same sample, so each have a stats file, but we only use the sample ID for making stats files), (this apply for long reads too).

Future self, I misread the `prefix` entry 😅

**Review by jfy133 — APPROVED** [review]

**Pull request merged**
