### PR TITLE
Fix KMCP profile being too strict in tests

### PR DESCRIPTION
**Pull request by jfy133**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/taxprofiler/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/taxprofiler _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by Midnighter** [comment]
Setting the mode to `0` in all configs even where we don't run KMCP seems overkill. Or is the intention here just in case we forget in future and do run it in another test profile?

**Comment by jfy133** [comment]
> Setting the mode to `0` in all configs even where we don't run KMCP seems overkill. Or is the intention here just in case we forget in future and do run it in another test profile?

The latter is correct - my thinking was we have to use that parameter setting whenever we will be using that particular database/samplesheet combination.

Maybe you want to do a quick test e.g. adapterremoval plus kmcp, so you use that profile but then override the run_kmcp = false so it executes, it would be better to ensure it doesn't fail due to a 'known' problem which could be mistakenly interpreted as some other issue with the pairing of the tools (basically a false positive)

**Comment by sofstam** [comment]
Do we need to document why we use the `kmcp_mode 0`?

**Review by sofstam — APPROVED** [review]
Do we need to document why we use `kmcp_mode 0`?

**Comment by jfy133** [comment]
Not for the tests no, can always look at the PR description is they want

**Pull request merged**
