### PR TITLE
Add ability to skip fastq/falco

### LINKED ISSUE #324: Add functionality to turn read QC on/off
### Description of feature

Hi,

Thank you for providing taxprofiler. It is a fantastic tool.

Sometimes I run the workflow and I don't want to have to run the FastQC/Falco step, either because I have already ran it before and am unable to get the `-resume` mechanism to pick it up, or I simply don't need it.

Would it be possible to add the functionality to turn it on/off, like with the adapter trimming step?

I have managed to deactivate it locally on my copy of the workflow. Would you welcome a PR attempting to add this functionality?

Thank you for any assistance you can provide.

Best,
Vini

### PR DESCRIPTION
**Pull request by jfy133**
closes #324 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/taxprofiler/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/taxprofiler _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jfy133** [comment]
Passes locally even if tests fail due to the upstream taxpasta bug(just waiting for the biocontainer)

**Review by mirpedrol — APPROVED** [review]
LGTM

**Comment by jfy133** [comment]
Thanks @mirpedrol ! I just merged in the fix for the CI test, so I'll marge that back in here and hopefully all the tests pass :)

**Review by Midnighter — APPROVED** [review]
Looks good to me 😃

**Pull request merged**
