### PR TITLE
Fix missing tag in MQC dynamic methods section and missing KMCP in taxpasta ouput

### PR DESCRIPTION
**Pull request by jfy133**
- missing tag Meant everything underneath was still the link
- Fxed typo kmcp in docs
- KMCP output now mixed in taxpasta
- Added additional 'useful' output file to full test (final reads for profiling) 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/taxprofiler/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/taxprofiler _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by Midnighter — DISMISSED** [review]
Neat, thanks 😃

**Comment by Midnighter** [comment]
Oh, actually, just looked at the failing run. It seems that a single profile is passed to `taxpasta merge` which then fails. So we need to apply the same logic as for other profilers.

**Comment by Midnighter** [comment]
And I should look at that profile. It seems like it's maybe completely empty and taxpasta doesn't like that. Might need to apply a minor fix to taxpasta. (Failing on a completely empty profile is not unreasonable, though.)

**Comment by jfy133** [comment]
Hmm ok maybe a bug both ends (agree not unreasonable but just staying: 'your profile is empty ' would be a better message).

If everyone behaves I'll try and investigate the empty file today

**Review by Midnighter — APPROVED** [review]
Code changes look good. We will need to update the KMCP database and fix taxpasta.

**Pull request merged**
