### PR TITLE
Delete extra unnecessary directory

### PR DESCRIPTION
**Pull request by sofstam**
I deleted the extra directory `nf-core/modules/centrifuge`

### CODE REVIEW

**Comment by sofstam** [comment]
I think it looks as it should in nf-core/modules repo. I am not sure why I ended up with this extra directory when I used `nf-core modules install` to add centrifuge module to taxprofiler.

**Comment by jfy133** [comment]
Is this an extra directory? It looks like it's the actual module?

image

We expect two centrfigue directories as we have `centrifuge`  as the umbrella dir for all subcommands? Then in this case the actual `centrifuge` sub-tool (the one we use to execute)

**Comment by sofstam** [comment]
Right now in `dev` there are two directories for modules. It does not seem right to me unless I misunderstand something :) 

Screenshot 2022-04-11 at 20 39 21

**Comment by jfy133** [comment]
Oh wow yes! Sorry I was on the wrong branch indeed :D

**Review by jfy133 — APPROVED** [review]

**Pull request merged**
